# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-16 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва кабінету')),
                ('number', models.CharField(max_length=15, verbose_name='Номер кабінету')),
                ('floor', models.CharField(max_length=10, verbose_name='Поверх')),
            ],
            options={
                'verbose_name': 'кабінет',
                'verbose_name_plural': 'Кабінети',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('surname', models.CharField(max_length=255, verbose_name='Прізвище')),
                ('name', models.CharField(max_length=255, verbose_name="Ім'я")),
                ('father_name', models.CharField(max_length=255, verbose_name='По-Батькові')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Електронна адреса')),
                ('cabinet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_queue_app.Cabinet')),
            ],
            options={
                'verbose_name': 'лікар',
                'verbose_name_plural': 'Лікарі',
            },
        ),
        migrations.CreateModel(
            name='Heap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_count', models.SmallIntegerField(default=1, verbose_name='Кількість сеансів')),
                ('procedure_finished_count', models.SmallIntegerField(default=0, verbose_name='Кількість завершених сеансів')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Час додавання в чергу')),
                ('first_seance_time', models.DateTimeField(auto_now_add=True, verbose_name='Час сеансу')),
            ],
            options={
                'verbose_name': 'запис',
                'verbose_name_plural': 'Записи',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Електронна адреса')),
                ('surname', models.CharField(max_length=255, verbose_name='Прізвище')),
                ('name', models.CharField(max_length=255, verbose_name="Ім'я")),
                ('father_name', models.CharField(max_length=255, verbose_name='По-Батькові')),
                ('date_of_birth', models.DateField(verbose_name='Дата народження')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер мобільного')),
                ('patient_status', models.IntegerField(choices=[(1, 'Звичайний'), (2, 'VIP'), (3, 'Нагальний')], default=1)),
                ('patient_present_state', models.SmallIntegerField(choices=[(1, 'відсутній'), (2, 'відійшов'), (3, 'в черзі'), (4, 'очікування'), (5, 'на процедурах')], default=1, verbose_name='Стан присутністі пацієнта')),
                ('patient_present_time', models.DateTimeField(auto_now_add=True, verbose_name='Час появи в черзі')),
                ('balance_of_funds', models.FloatField(default=0.0, verbose_name='Баланс коштів')),
            ],
            options={
                'verbose_name': 'пацієнт',
                'verbose_name_plural': 'Пацієнти',
            },
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва процедури')),
                ('available_to_registrars', models.BooleanField(default=False, verbose_name='Дана професія є доступною для реєстраторів')),
                ('cost', models.FloatField(default=0.0, verbose_name='Вартість процедури')),
                ('doctors', models.ManyToManyField(to='hospital_queue_app.Doctor', verbose_name='Лікарі які проводять процедуру')),
                ('incompatible_procedures', models.ManyToManyField(blank=True, to='hospital_queue_app.Procedure', verbose_name='Несумісні процедури')),
            ],
            options={
                'verbose_name': 'процедура',
                'verbose_name_plural': 'Проседури',
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession_name', models.CharField(max_length=255, verbose_name='Назва професії')),
                ('profession_description', models.TextField(blank=True, null=True, verbose_name='Повний опис професії')),
            ],
            options={
                'verbose_name': 'професія',
                'verbose_name_plural': 'Професії',
            },
        ),
        migrations.CreateModel(
            name='HistoryHeap',
            fields=[
                ('heap_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hospital_queue_app.Heap')),
            ],
            options={
                'verbose_name': 'виконаний запис',
                'verbose_name_plural': 'Історія записів',
            },
            bases=('hospital_queue_app.heap',),
        ),
        migrations.AddField(
            model_name='heap',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_queue_app.Doctor', verbose_name='Лікар'),
        ),
        migrations.AddField(
            model_name='heap',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_queue_app.Patient', verbose_name='Пацієнт'),
        ),
        migrations.AddField(
            model_name='heap',
            name='procedure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_queue_app.Procedure', verbose_name='Процедура'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_queue_app.Profession'),
        ),
        migrations.AlterUniqueTogether(
            name='heap',
            unique_together=set([('patient', 'procedure')]),
        ),
    ]
